# Generated by Django 3.1.6 on 2021-04-03 07:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gsms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_old_quantity', models.PositiveIntegerField()),
                ('material_in_qty', models.IntegerField()),
                ('material_out_qty', models.IntegerField()),
                ('material_change_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackingListChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_weight', models.PositiveIntegerField()),
                ('weight_out', models.IntegerField()),
                ('packing_change_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Pallet',
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['material_name']},
        ),
        migrations.AlterModelOptions(
            name='packinglist',
            options={'ordering': ['packing_no']},
        ),
        migrations.RenameField(
            model_name='material',
            old_name='material_no',
            new_name='material_name',
        ),
        migrations.RenameField(
            model_name='packinglist',
            old_name='material_no',
            new_name='material_name',
        ),
        migrations.AddField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='material_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packinglist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packinglistchangehistory',
            name='packing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gsms.packinglist'),
        ),
        migrations.AddField(
            model_name='materialchangehistory',
            name='material_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gsms.material'),
        ),
    ]
