# Generated by Django 3.2 on 2021-05-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsms', '0002_auto_20210403_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='packinglist',
            name='transfer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gsms.transferlocation'),
        ),
    ]
