# Generated by Django 3.2 on 2021-05-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsms', '0003_auto_20210520_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferlocation',
            name='id',
        ),
        migrations.AddField(
            model_name='transferlocation',
            name='description',
            field=models.TextField(default='Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferlocation',
            name='name',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
